### ISSUE TITLE
[Feature Request] Add it to AUR

### ISSUE THREAD

**Issue by Toadfield** [MTrage/Borg-BackUP-GUI#12]
That would be cool.

**Comment by ojaksch** [comment]
Freshly baked. Have a look at https://aur.archlinux.org/packages/borg-backup-gui-git/ and give it a try,

**Comment by MTrage** [comment]
very good idea!

The GUI still needs a fixed path for the folders "export", "images" and "profiles", e.g. in a folder like "~/.config/Borg-BackUP-GUI". I will take a closer look at this in the next few days.

**Comment by ojaksch** [comment]
Great. Just gimme a sign and I'll update the AUR package, if necessary.

**Comment by Toadfield** [comment]
I installed it,but if I search for it in krunner,I don't see an shortcut.

**Comment by ojaksch** [comment]
It's missing a .desktop file. I'll create one for the next update.

**Comment by MTrage** [comment]
> Great. Just gimme a sign and I'll update the AUR package, if necessary.

Ok, I have changed it. Now, during the installation process, the folder "~/.config/Borg-BackUP-GUI/" must be created and the orders of "src" copied into it.

**Comment by ojaksch** [comment]
...wouldn't it be more useful that Borg-BackUP-GUI checks and creates ~/.config/Borg-BackUP-GUI at launch in users home?
I mean, I have to use a startup helper script otherwise that will doing that and starts the GUI afterwards - but this would be a wasteful step in my opinion.

**Comment by MTrage** [comment]
The problem I have is the "loading.gif" which is in the "src/images". I can check the folders at the first start, and create them if necessary, but how can I copy this one "loading.gif" file cleanly into it? The "loading.gif" (animation) is the only image file which I unfortunately cannot integrate directly into Qt with Base64.

**Comment by ojaksch** [comment]
I see...but can't help. But, well, then let's doing the way of my startup helper script for the time until you can fix this issue.
Where to copy src/images/loading.gif to? Any other path under ~/.config/Borg-BackUP-GUI I shall check for?

**Comment by MTrage** [comment]
I will test something this evening, which should solve all the problems. Then you won't have to change anything extra and I'll know one more workaround. °) I'll be back

**Comment by ojaksch** [comment]
I'm keeping my fingers crossed for you :) And if it does not work, I have anything else ready...it's an easy task to expand and update this helper script.

**Comment by MTrage** [comment]
I'm ready! 
The secret is that Qt can load and display GIF files (also animations) but cannot save them as images or animations – so the possibility to include a Base64-GIF animation in Qt and then save it to the target directory is dead! 

Therefore I use the following **workaround**, the GUI asks if a "~/.config/Borg...." exists and if not it creates it and the subdirectories and copies the data from GitHub with **wget** into the target directory.

The user must also have **wget** installed (I think it should be standard) - so it is sufficient to start "/usr/bin/BORG-BackUP-GUI" and everything important will be done automatically in the background.

**Comment by ojaksch** [comment]
Congrats! Looks like the same way as my helper script would dispatch this.
  I can see that you're downloading some more stuff. Great that the app is doing that now. Dealing with these things in a users home while building/installing the app is a conceivably bad idea as you'll never know who and how many users will going to use this app :)
I've updated the AUR package. Next thing is a problem of core dump while exiting the app, but I'll open a new issue for that.

**Comment by MTrage** [comment]
Originally I only wanted to help 2 friends with this GUI, but then I noticed that there was no GUI for Borg Backup yet. So I was the first to provide a GUI for Borg Backup, but the target group was too much trouble to install it; but thanks to you this will now help some.

_Thanks again and keep up the good work._

**Comment by ojaksch** [comment]
> I noticed that there was no GUI for Borg Backup yet

Erm, no. There is [Vorta](https://github.com/borgbase/vorta) :wink: Is it a good/easy GUI? Dunno. But it's always good to have a choice.
Always at your service!

**Comment by MTrage** [comment]
**Yes there is, Vorta, and it is certainly very good.**

I was not being mean, but only from the point of view of a user who is looking for a quick and easy solution.

_I have to say though, if you had told me how much time it would take to develop such a GUI, I would have immediately started 
gargling with nitroglycerine._ °)

**Comment by ojaksch** [comment]
Absolutely comprehensible. And yes, that's one of the many reasons why I'm "avoiding" to start, rather continuing, in programming since decades (did some assembler at 6502), so I'm still satisfied with doing Bash magics :)

**Comment by MTrage** [comment]
6502 every mistake cost money! °) – I only say assembler on the Amiga!!!
I not only killed the CPU but also successfully killed Blitter, Copper and the read head of the floppy drive. °)

**_Back then you were annoyed, but today you wish the old days were back again._**

**Comment by ojaksch** [comment]
> Back then you were annoyed, but today you wish the old days were back again.

Yes, exactly. And that one of the reasons why I've built my own Atari 1088XEL a few months ago.

**Comment by MTrage** [comment]
Please write to my email (mt@7vm.de) and I will send you my qTox data - should make life easier!
