### ISSUE TITLE
video / docs

### ISSUE THREAD

**Issue by ThomasWaldmann** [MTrage/Borg-BackUP-GUI#4]
maybe remove the link to borgbackup video and docs and rather have 1 link to either borgbackup github site or borgbackup.org.

if you link to a video / docs, users would rather expect to see video/docs about `borg-backup-gui` here, not about `borgbackup`.

**Comment by MTrage** [comment]
That's a good idea. From the point of view of the benefit, this is certainly somewhat confusing.

My intuition was to push Borg more.
