### ISSUE TITLE
Missing build instructions

### ISSUE THREAD

**Issue by erikzenker** [MTrage/Borg-BackUP-GUI#7]
Is there a way to build the application binary by myself? I am missing makefiles or cmake files.

**Comment by MTrage** [comment]
You change to the src directory and type qmake and then make.

`cd Borg-BackUP-GUI/src/`
` qmake && make`

I have also described here (https://github.com/MTrage/Borg-BackUP-GUI/wiki/Short-instruction), but I admit it is a bit confusing. 

You can also make further individual adjustments in advance with Qt Designer or Qt Creator.

**Comment by erikzenker** [comment]
Could you please add the `style.qrc` file to the repo?
```
erik@Excelsior ~/p/B/src> qmake
Info: creating stash file /home/erik/projects/Borg-BackUP-GUI/src/.qmake.stash
WARNING: Failure to find: qdarkstyle/style.qrc
/usr/bin/rcc: File does not exist 'qdarkstyle/style.qrc'
```

**Comment by MTrage** [comment]
Moved to new issues: https://github.com/MTrage/Borg-BackUP-GUI/issues/8
